"absolute" => "relative" IRI.
w3c/rdf-turtle pull request #38
Opened 2023-08-20 19:54 UTC by gkellogg

Also, define "prefixed name" as a term.

2023-08-20 20:05 UTC, afs commented on spec/index.html
> +      Relative and resolved IRIs are preceded by <code>&lt;</code> (code point <span class="codepoint">U+003C</span>),
That's an "URI-reference" in RFC 3986 speak. 
But using the RDF 1.2 names for consistency across documents is fine.

2023-08-21 20:23 UTC, TallTed requested changes
Tiny fix

2023-08-21 20:23 UTC, TallTed commented on spec/index.html
>          The datatype IRI in Turtle may be written using either an
```suggestion
        The datatype IRI in Turtle may be written using either a
```

2023-08-21 21:21 UTC, afs approved these changes

2023-08-31 20:03 UTC, merged