Favor the use of PREFIX and BASE
w3c/rdf-turtle pull request #41
Opened 2023-09-18 21:06 UTC by gkellogg

2023-09-18 21:25 UTC, domel reviewed
> No decoding is necessary if the HTML document has already been parsed into DOM. Each script data block is considered to be it's own Turtle document.
PREFIX and BASE declarations in a Turtle data bloc

Doesn't the above fragment suggest that the rule only applies to `PREFIX` and `BASE` and not to `@prefix` and `@base`?

2023-09-18 21:25 UTC, domel commented on spec/index.html
> +      <code>PREFIX</code> and <code>BASE</code> declarations in a Turtle data bloc
data bloc -> data block

2023-09-18 21:25 UTC, domel commented on spec/index.html
> -      <code>@prefix</code> and <code>@base</code> declarations in a Turtle data bloc
data bloc -> data block

2023-09-18 21:31 UTC, TallTed requested changes

2023-09-18 21:31 UTC, TallTed commented on spec/index.html
> +     PrEfIx : <http://another.example/>       # empty prefix
```suggestion
      PrEfIx : <http://another.example/>       # empty prefix
```

2023-09-18 21:31 UTC, TallTed commented on spec/index.html
>        Each <code>script</code> data block is considered to be it's own Turtle document.
```suggestion
      Each <code>script</code> data block is considered to be its own Turtle document.
```

2023-09-18 22:23 UTC, gkellogg commented on spec/index.html
> +      <code>PREFIX</code> and <code>BASE</code> declarations in a Turtle data bloc
```suggestion
      <code>PREFIX</code> and <code>BASE</code> declarations in a Turtle data block
```

2023-09-19 08:19 UTC, domel approved these changes

2023-09-21 20:53 UTC, merged