Fix grammar tokens
w3c/rdf-turtle pull request #47
Opened 2023-10-06 23:02 UTC by gkellogg

2023-10-07 07:04 UTC, domel approved these changes

2023-10-12 18:09 UTC, TallTed requested changes

2023-10-12 18:09 UTC, TallTed commented on spec/index.html
>          or use mixed case.
```suggestion
        and can be written as <a href="#grammar-production-sparqlPrefix"><code>prefix</code></a> and <a href="#grammar-production-sparqlBase"><code>base</code></a>
        or as any blend of mixed case.
```

2023-10-12 21:25 UTC, merged

2023-10-13 04:43 UTC, TallTed commented on spec/index.html
>      <a data-cite="RDF12-CONCEPTS#dfn-blank-node">blank nodes</a>, and.
Note: errant `.` at end of line 294, which should replace `,` and end of line 295. (Alternatively, `,` at end of line 295 could be changed to `;`)