Processing updates
w3c/rdf-turtle pull request #68
Opened 2024-09-07 21:45 UTC by gkellogg

* Update Turtle grammar for Triple Term to be `<<(ttSubject verb ttObject)>>` instead of `<<(ttSubject predicate ttObject)>>`. This allows `a` in addition to an IRI.
* Save and restore curTripleTerm in Annotation Blocks and Reified Triples.
* Fix some HTML validator warnings.

Fixes #67.

2024-09-09 09:58 UTC, afs approved these changes

2024-09-09 10:43 UTC, domel approved these changes

2024-09-09 18:27 UTC, TallTed requested changes
punctuation, typo, and language

2024-09-09 18:27 UTC, TallTed commented on spec/index.html
> +      and then restores the recorded value of the |curTripleTerm|.
```suggestion
      it next yields the RDF triple |curReifier| <code>rdf:reifies</code> |curTripleTerm|,
      and then restores the recorded value of the |curTripleTerm|.
```

2024-09-09 18:27 UTC, TallTed commented on spec/index.html
> +      If the |curReifier| is not set, then the |curReifier| is assigned a fresh RDF <a data-cite="RDF12-CONCEPTS#dfn-blank-node">blank node</a>
```suggestion
      If the |curReifier| is not set, then it is assigned a fresh RDF <a data-cite="RDF12-CONCEPTS#dfn-blank-node">blank node</a>
```

2024-09-09 18:27 UTC, TallTed commented on spec/index.html
>        Finishing the <a href="#grammar-production-annotationBlock"><code>annotationBlock</code></a> production,
```suggestion
      Finishing the <a href="#grammar-production-annotationBlock"><code>annotationBlock</code></a> production
```

2024-09-09 18:27 UTC, TallTed commented on spec/index.html
> +      clears the value of the |curReifier|,
```suggestion
      clears the value of the |curReifier|
```

2024-09-09 18:27 UTC, TallTed commented on spec/index.html
> +      reifyiing triple |curReifier| <code>rdf:reifies</code> |curTripleTerm|
```suggestion
      reifying triple |curReifier| <code>rdf:reifies</code> |curTripleTerm|
```

2024-09-12 16:27 UTC, merged

2024-09-12 17:09 UTC, pchampin commented
This was discussed during the [#rdf-star meeting on 12 September 2024](https://www.w3.org/2024/09/12-rdf-star-minutes.html#t07).

<details><summary><i>View the transcript</i></summary>

#### [w3c/rdf-turtle#68](https://github.com/w3c/rdf-turtle/issues/68) and [w3c/rdf-trig#33](https://github.com/w3c/rdf-trig/issues/33)
<cite>gkellogg:</cite> second item (updates to turtle). I think that's ready to merge.
  
  

----
</details>

2024-09-12 17:24 UTC, pchampin commented
This was discussed during the [rdf-star meeting on 12 September 2024](https://www.w3.org/2024/09/12-rdf-star-minutes.html#t07).

<details><summary><i>View the transcript</i></summary>

#### [w3c/rdf-turtle#68](https://github.com/w3c/rdf-turtle/issues/68) and [w3c/rdf-trig#33](https://github.com/w3c/rdf-trig/issues/33)


<cite>gkellogg:</cite> second item (updates to turtle). I think that's ready to merge.
  
  


<cite>ora:</cite> you're saying someone else should take a look before a merge?


<cite>gkellogg:</cite> yes. look and approve. then we can merge after that.


<cite>AndyS:</cite> I can. Have done changes to the trig parser.


<cite>&lt;pchampin&gt;</cite> subtopic [w3c/sparql-federated-query#20](https://github.com/w3c/sparql-federated-query/issues/20)


<cite>ora:</cite> what about federated sparql error fix?


<cite>AndyS:</cite> it has 3 approvals.


<cite>ora:</cite> I think we should merge it. Not sensing that it needs waiting anymore.


<cite>AndyS:</cite> I can sort that out.


<cite>ora:</cite> any others for today?


----
</details>