Use better BIDI examples.
w3c/rdf-turtle pull request #78
Opened 2024-10-24 22:40 UTC by gkellogg

Fixes #75.

2024-10-25 06:49 UTC, iherman approved these changes
We should flag this explicitly for the upcoming a11y review to see if this is all right. I am always messed up: should we see here what is displayed properly or what is stored in memory? I guess it is the former.

2024-10-25 06:55 UTC, domel approved these changes
Quite simple editions. Agree.

2024-10-25 08:12 UTC, afs approved these changes

2024-10-25 14:33 UTC, TallTed requested changes

2024-10-25 14:33 UTC, TallTed commented on spec/index.html
> +                               and up to two sequential apostrophes ('').''' .
```suggestion
                               literal with many quotes (""""")
                               and up to two sequential apostrophes ('').''' . # literal with embedded new lines and quotes
```

2024-10-25 14:33 UTC, TallTed commented on spec/index.html
>          show:218 show:blurb '''This is a multi-line                        # literal with embedded new lines and quotes
Moving the comment *outside* the literal.
```suggestion
        show:218 show:blurb '''This is a multi-line
```

2024-10-28 17:10 UTC, TallTed requested changes

2024-10-28 17:10 UTC, TallTed commented on spec/index.html
>          show:218 show:localName "Cette Série des Années Septante"@fr-be .  # literal with a region subtag
realign the right-side comments. Similar should be done to the 5 lines above these.
```suggestion
        show:218 show:localName "That Seventies Show"@en-us--ltr .           # literal with a language tag, region subtag, and base direction
        show:218 show:localName 'Cette Série des Années Soixante-dix'@fr .   # literal delimited by single quote
        show:218 show:localName "Cette Série des Années Septante"@fr-be .    # literal with a region subtag
```

2024-10-28 17:30 UTC, merged